---
jobs:
- name: job-bump-version
  public: true
  serial: true
  plan:
  - get: app-version
    trigger: false
    resource: resource-app-version
    params:
      bump: patch
  - put: app-version
    resource: resource-app-version
    params:
      file: app-version/number
  - task: display-version
    config:
      platform: linux
      image: docker:///ubuntu#14.04
      inputs:
      - name: app-version
      run:
        path: cat
        args: [app-version/number]

resources:
- name: resource-app-version
  type: semver
  source:
    bucket: concourse-tutorial-app-version-pipeline
    key: app-version
    initial_version: 1.0.0
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: us-east-1
