---
jobs:
  - name: show-animal-names
    plan:
      - task: show-animal-names
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}
          run:
            path: env
            args: []
          params:
            CAT_NAME: ((cat-name))
            DOG_NAME: ((dog-name))
