---
jobs:
- name: job-spiff-merge
  public: true
  serial: true
  plan:
  - aggregate:
    - get: stub
      resource: resource-deployment-manifest-stub
    - get: redis-release
      resource: resource-redis-release-templates
      params:
        submodules: none
  - task: spiff-merge
    config:
      platform: linux
      image: docker:///drnic/spiff
      inputs:
      - name: redis-release
      - name: stub
      run:
        path: spiff-merge-and-save
        args:
          - manifest.yml
          - redis-release/templates/deployment.yml
          - redis-release/templates/jobs.yml
          - redis-release/templates/infrastructure-aws-ec2.yml
          - stub/stub.yml
  - task: show-manifest
    config:
      platform: linux
      image: docker:///drnic/spiff
      inputs:
      - name: spiff-merge
      run:
        path: cat
        args: ["spiff-merge/manifest.yml"]

resources:
- name: resource-cf-release-templates
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git

- name: resource-redis-release-templates
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/redis-boshrelease.git

- name: resource-deployment-manifest-stub
  type: git
  source:
    uri: https://gist.github.com/638a2e7051071b3bbec7.git
