---
jobs:
- name: job-spiff-merge
  public: true
  serial: true
  plan:
  - aggregate:
    - get: stub
      resource: resource-deployment-manifest-stub
    - get: redis-release
      resource: resource-redis-release-templates
      params:
        submodules: none
    - get: resource-tutorial
  - task: spiff-merge
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: drnic/spiff}
      inputs:
      - name: redis-release
      - name: stub
      - name: resource-tutorial
      run:
        path: resource-tutorial/46_bosh_manifest_spiff_merge/spiff-merge-and-save.sh
        args:
          - spiff-merge/manifest.yml
          - redis-release/templates/deployment.yml
          - redis-release/templates/jobs.yml
          - redis-release/templates/infrastructure-aws-ec2.yml
          - redis-release/templates/stub.yml
      outputs:
      - name: spiff-merge
  - task: show-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: drnic/spiff}
      inputs:
      - name: spiff-merge
      run:
        path: cat
        args: ["spiff-merge/manifest.yml"]

resources:
- name: resource-redis-release-templates
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/redis-boshrelease.git

- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: fix-46-spiff-merge

- name: resource-deployment-manifest-stub
  type: git
  source:
    uri: https://gist.github.com/638a2e7051071b3bbec7.git
