---
jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-web-app
  - aggregate:
    - put: resource-deploy-web-app
      params:
        manifest: resource-web-app/manifest.yml
        path: resource-web-app

resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: drnic@starkandwayne.com
    password: UHUst0ck
    organization: starkandwayne
    space: concourse-experiments
    skip_cert_check: false
