---
jobs:
- name: job-build-bosh-init-cli
  public: true
  serial: true
  plan:
  - aggregate:
    - get: bosh-init
      resource: git-bosh-init
  - task: bosh-init-cli-build
    config:
      platform: linux
      image: docker:///concourse/static-golang
      inputs:
        - name: bosh-init
          path: gopath/src/github.com/cloudfoundry/bosh-init
      run:
        path: gopath/src/github.com/cloudfoundry/bosh-init/bin/build
  - put: s3-bosh-init
    params:
      from: bosh-init-cli-build/gopath/src/github.com/cloudfoundry/bosh-init/out/bosh-init

- name: job-repackage-bosh-init-aws
  public: true
  serial: true
  plan:
  - aggregate:
    - get: s3-bosh-init
      passed: [job-build-bosh-init-cli]
    - get: cpi
      resource: git-bosh-init-aws-cpi
  - task: prepare-aws-docker-image
    file: cpi/build.yml
  - put: bosh-init-aws-docker-image
    params:
      build: prepare-aws-docker-image/cpi

resources:
- name: git-bosh-init
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-init.git
    branch: master
- name: s3-bosh-init
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: {{aws-region-name}}
    bucket:  {{aws-bosh-init-bucket}}
    private: false

- name: git-bosh-init-aws-cpi
  type: git
  source:
    uri: https://gist.github.com/db1126b8456bcaa854f3.git

- name: bosh-init-aws-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-bosh-init-aws}}
