---
jobs:
- name: job-deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
    - get: resource-bosh-release-redis
    - get: resource-manifest
  - put: resource-redis-bosh-deployment
    params:
      manifest: resource-manifest/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz
resources:
- name: resource-manifest
  type: git
  source:
    uri: https://gist.github.com/mkb/30c002a6ed185ed1bb100edbfa8b8ac9
    # uri: https://gist.github.com/3ff87c465d483543c53d.git # AWS example

- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}

- name: resource-bosh-release-redis
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/redis-boshrelease

- name: resource-redis-bosh-deployment
  type: bosh-deployment
  source:
    target: {{bosh-director}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: redis # from the manifest.yml in resource-manifest
    ignore_ssl: true
