---
jobs:
- name: job-build-task-image
  public: true
  serial: true
  plan:
  - get: resource-tutorial
    resource: resource-tutorial-section-47
  - put: task-docker-image
    params:
      build: resource-tutorial/47_spiff_merge_redis_to_bosh_lite/task_docker_image

resources:
- name: resource-tutorial-section-47
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: master

- name: task-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-47-tasks}}
