---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/starkandwayne/concourse-tutorial.git
      branch: develop
  - name: app
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

  - name: deploy-web-app
    type: cf
    source:
      api: ((cf-api))
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-organization))
      space: ((cf-space))
      skip_cert_check: true

jobs:
  - name: deploy-app
    public: true
    serial: true
    plan:
      - get: tutorial
      - get: app
        trigger: true
      - task: web-app-tests
        config:
          platform: linux

          image_resource:
            type: registry-image
            source: {repository: golang, tag: 1.9-alpine}

          inputs:
            - name: tutorial
            - name: app
              path: gopath/src/github.com/cloudfoundry-community/simple-go-web-app

          run:
            path: tutorial/tutorials/basic/job-inputs/task_run_tests.sh
      - put: deploy-web-app
        params:
          manifest: app/manifest.yml
          path: app
