#!/bin/bash

dir=$1; shift
if [[ "${dir}X" == "X" ]]; then
  echo "USAGE: git-add-all path/to/git/repo"
  exit 1
fi

set -e

git config --global user.email "nobody@concourse.ci"
git config --global user.name "Concourse"

pushd $dir
  echo "Checking for changes..."
  if [[ "$(git status -s)X" != "X" ]]; then
    git add .
    git commit -m "Generate manifest from stub change"
  fi
popd
