---
jobs:
  - name: shield
    public: true
    serial: true
    plan:
      - get: github-release-shield
      - task: ls
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: ubuntu}
          inputs:
            - name: github-release-shield
          run:
            path: ls
            args: ["-opR", "."]
      - task: version
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: ubuntu}
          inputs:
            - name: github-release-shield
          run:
            path: cat
            args: [github-release-shield/version]
resources:
  - name: github-release-shield
    type: github-release
    source:
      user: starkandwayne
      repository: shield
