---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pivnet-stemcells
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: stemcells

jobs:
- name: stemcells
  public: true
  plan:
  - get: pivnet-stemcells
    trigger: true
  - task: show-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs: [{name: pivnet-stemcells}]
      run:
        path: cat
        args: [pivnet-stemcells/version]
  - task: show-metadata-yaml
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs: [{name: pivnet-stemcells}]
      run:
        path: cat
        args: [pivnet-stemcells/metadata.yaml]
