---
meta:
  aws:
    access_key_id: (( merge ))
    secret_access_key: (( merge ))

jobs:
- name: job-bump-version
  public: true
  serial: true
  plan:
  - get: app-version
    resource: resource-app-version
    params:
      pre: rc
  - put: app-version
    params:
      file: app-version/number
  # - task: display-version
  #   config:
  #     platform: linux
  #     image: docker:///ubuntu#14.04
  #     inputs:
  #     - name: app-version
  #     run:
  #       path: cat
  #       args: [app-version/number]

resources:
- name: resource-app-version
  type: semver
  source:
    bucket: concourse-tutorial-app-version-pipeline
    key: app-version
    initial_version: 1.0.0
    access_key_id: (( meta.aws.access_key_id ))
    secret_access_key: (( meta.aws.secret_access_key ))
    region_name: us-east-1
