---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/starkandwayne/concourse-tutorial.git
      branch: develop

jobs:
  - name: test
    public: true
    serial: true
    plan:
      - get: tutorial
        trigger: true
      - task: test-sometimes-works
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: tutorial
          run:
            path: tutorial/tutorials/miscellaneous/slack-notifications/test-sometimes-works.sh
